# Copyright 2018 ETH Zurich and University of Bologna.
# Copyright and related rights are licensed under the Solderpad Hardware
# License, Version 0.51 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
# or agreed to in writing, software, hardware and materials distributed under
# this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Author: Michael Schaffner <schaffner@iis.ee.ethz.ch>, ETH Zurich
# Date: 26.11.2018
# Description: GitLab CI configuration script.

before_script:
        #- git submodule update --init --recursive
  - export PITON_ROOT=`pwd`
  - export ARIANE_ROOT=${PITON_ROOT}/piton/design/chip/tile/ariane/
  - export PATH=$RISCV/bin:$PATH
  - source /opt/Xilinx/Vivado/2020.1/settings64.sh

  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - tools
  - protosyn
  - fpga

###################################
# setup tools

tools:build:
  tags: 
    - MEEP_FPGA 
  stage: tools
  script:
    - source piton/ariane_setup.sh
      #    - source ariane_build_tools.sh
    - git clone https://github.com/riscv/riscv-gnu-toolchain riscv_toolchain
    - cd riscv_toolchain
    - ./configure --prefix=$PITON_ROOT/riscv
    - protosyn --board alveou280 --design system --core ariane --x_tiles 1 --y_tiles 1 --uart-dmw ddr --zeroer_off

   artifacts:
       when: always
       paths: $PITON_ROOT/build/alveou280/system/protosyn_logs/make_project.log

