# Copyright 2018 ETH Zurich and University of Bologna.
# Copyright and related rights are licensed under the Solderpad Hardware
# License, Version 0.51 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
# or agreed to in writing, software, hardware and materials distributed under
# this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Author: Michael Schaffner <schaffner@iis.ee.ethz.ch>, ETH Zurich
# Date: 26.11.2018
# Description: GitLab CI configuration script.

before_script:
  - git submodule update --init --recursive
  - export PITON_ROOT=`pwd`
  # paths to local or network installations (the riscv toolchain is not built in the ci job as in travis)
  # (license setup is then done by the SEPP startup script)
  #- eval "function vcs() { command vcs-2017.03-kgf vcs -full64 \"\$@\"; };"
  #- export -f vcs
  - export VCS_HOME="/eda/synopsys/2020-21/RHELx86/VCS_2020.12"
  #- export MODELSIM_VERSION="-10.6b -64"
  #- export MODELSIM_HOME="/usr/pack/modelsim-10.6b-kgf/"
  - export VIVADO_BIN="/opt/Xilinx/Vivado/2020.1/bin/"
  - export CXX=g++ CC=gcc
  - export RISCV=/tmp/scratch2/gitlabci/riscv_install
  - export VERILATOR_ROOT=/tmp/scratch2/gitlabci/verilator-4.014/
  - export PATH=$PATH:${RISCV}/bin:$VERILATOR_ROOT/bin
  - export LIBRARY_PATH=$RISCV/lib
  - export LD_LIBRARY_PATH=$RISCV/lib
  - export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  - export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  - export ARIANE_ROOT=${PITON_ROOT}/piton/design/chip/tile/ariane/
  # this is for sims batches
  - export DRMJOBSCRATCHSPACE=/tmp/scratch2/gitlabci/tmp/
  # set_ev riscv_vector_toolchange
  - export RISCV_VEC_TOOL_VER=rvv-0.7.1
  - export RISCV=$RISCV_VEC_TOOL
  - export RISCV_VEC_TOOL=/home/tools/riscv_vector_toolchain/$RISCV_VEC_TOOL_VER
  - export PATH=$RISCV/bin:$PATH
  # eda env
  - export CDS_LCU=/eda/cadence/licenses/bin/LCU_4.30.002
  - export PATH="${PATH}:${CDS_LCU}/RHELx86/tools.lnx86/bin"
  # eda env  cadence
  - . environment/cadence/scripts/SPECTRE_19.10.541_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/VMANAGER_20.03.005_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/INDAGO_20.09.001_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/XCELIUM_20.09.001_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/CONFRML_20.10.200_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/INNOVUS_20.11.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/GENUS_19.14.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/SSV_20.11.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/MODUS_19.12.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/LIBERATE_19.21.591_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/PVS_19.15.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/QUANTUS_20.12.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/MVS_20.11.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/IC_6.1.8.140_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/ASSURA_04.16.109_618_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/INTEGRAND_60.00.000_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/JLS_19.15.000_RHELx86.sh
  - . environment/cadence/scripts/SIG_19.00.003_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/SPB_17.40.011_RHELx86.sh
  - . /eda/cadence/2020-21/scripts/SSV_20.11.000_RHELx86.sh
  - . environment/cadence/scripts/VIPCAT_11.30.072_RHELx86.sh
  # eda env cadence licence
  - export CDS_LIC_FILE=5280@eda03.bsc.es
  - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$CDS_LIC_FILE
  # eda env synopsys
  - . /eda/synopsys/2020-21/scripts/CORETOOLS_2020.12-1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/CUSTOM-SIM_2020.12-1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/CUSTOM-WV_2020.12_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/ESP_2020.09-SP1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/EUCLIDE_2020.12-1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/FM_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/ICC_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/ICC2_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/ICV_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/ICVWB_2020.09-SP1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/LC_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/MW_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/NT_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/PROTOCOMP_2020.03-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/PT_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/SFPGA_2020.09-SP1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/SILICONSMART_2020.12_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/SILVER_2020.06-SP1_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/SPYGLASS_2020.12_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/STARRC_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/SYN_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/TMAX_2020.09-SP2_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/VCS_2020.12_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/VC-STATIC_2020.12_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/VERDI_2020.12_RHELx86.sh
  - . /eda/synopsys/2020-21/scripts/VIP_2020.12_RHELx86.sh
  # eda env synopsys licence
  - export SNPS_LICENSE_FILE=27020@epi01.bsc.es
  - export SNPSLMD_LICENSE_FILE=27020@epi01.bsc.es
  - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$SNPS_LICENSE_FILE:$SNPSLMD_LICENSE_FILE
  # eda env mentor
  - . /eda/mentor/2020-21/scripts/QUESTA-CORE-PRIME_2020.4_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/AMSV_2020.4_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/CALIBRE_2020.4.15.9_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/CATAPULT_10.5c_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/FPRO_2020.1_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/HDL-DESIGNER_2020.4_RHELx86.sh
  #- . environment/mentor/scripts/HLVX_2.7.U3_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/LEONARDO_2020a_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/NITRO-SOC_2020.2.R1_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/OASYS-RTL_2020.1.R1_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/PRECISION_2020.1_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/QUESTA-CDC-FML_2020.4_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/QUESTA-INFACT_2020.4_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/QUESTA-VIP_2020.4_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/REQTRACER_2020.4_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/TANNER_2020.1.U6_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/TESSENT_2020.3_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/VISTA_2020.3_RHELx86_32.sh
  - . /eda/mentor/2020-21/scripts/VISTA_2020.3_RHELx86_64.sh
  - . /eda/mentor/2020-21/scripts/VISUAL-ELITE_2020.3_RHELx86.sh
  - . /eda/mentor/2020-21/scripts/X-ENTP-VX_2.7.U8_RHELx86.sh
  - export QUESTA_HOME=/eda/mentor/2020-21/RHELx86/QUESTA-CORE-PRIME_2020.4
  # eda env mentor licence 
  - export MGLS_LICENSE_FILE=1717@epi03.bsc.es
  - export MGLS1_LICENSE_FILE=1717@epi01.bsc.es
  - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$MGLS_LICENSE_FILE:$MGLS1_LICENSE_FILE

  # eda env imperas
  - export IMPERAS_HOME=/eda/imperas/Imperas.20210408
  - export IMPERAS_PERSONALITY=CPUMAN_MULTI
  - export IMPERAS_UNAME=Linux
  - export IMPERAS_ARCH=Linux64
  - export IMPERAS_SHRSUF=so
  - export IMPERAS_VLNV=${IMPERAS_HOME}/lib/${IMPERAS_ARCH}/ImperasLib
  - export IMPERAS_RUNTIME=CpuManager
  - export LD_LIBRARY_PATH=$IMPERAS_HOME/bin/$IMPERAS_ARCH:$IMPERAS_HOME/lib/$IMPERAS_ARCH/External/lib
  - export PATH=$PATH:$IMPERAS_HOME/bin/$IMPERAS_ARCH
  - . environment/imperas/setup.sh
  - setupImperas /eda/imperas/imperas.20210408
  # eda env imperas
  - export IMPERASD_LICENSE_FILE=2700@eda03.bsc.es
  - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$IMPERASD_LICENSE_FILE
  # piton setup
  - . ./piton/piton_settings.bash
  # setup python
  - export PITON_ROOT=`pwd`
  - export LAGARTO_ROOT=${PITON_ROOT}/piton/design/chip/tile/meep_vas_tile_core/
  - export ARIANE_ROOT=${PITON_ROOT}/piton/design/chip/tile/ariane/
    ## GCC and RISCV GCC setup
  - export CXX=g++ CC=gcc
    # customize this to a fast local disk
  - export RISCV=/scratch/`whoami`/riscv_install
  - export VERILATOR_ROOT=$ARIANE_ROOT/tmp/verilator-4.014/
    # setup paths
  - export PATH=$RISCV/bin:$VERILATOR_ROOT/bin:$PATH
  - export LIBRARY_PATH=$RISCV/lib
  - export LD_LIBRARY_PATH=$RISCV/lib
  - export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  - export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include

# source OpenPiton setup script
# note: customize this script to reflect your tool setup
  - . ./piton/piton_settings.bash
  - export RISCV=/home/tools/openpiton/riscv_install
  - export VERILATOR_ROOT=/home/tools/openpiton/open-piton/piton/design/chip/tile/ariane/tmp/verilator-4.014/
  - export PATH=$RISCV/bin:$VERILATOR_ROOT/bin:$PATH
  - export LIBRARY_PATH=$RISCV/lib
  - export LD_LIBRARY_PATH=$RISCV/lib
  - export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  - export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  - export MODELSIM_HOME=/eda/mentor/2020-21/RHELx86/QUESTA-CORE-PRIME_2020.4 

  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - tools
  - build:lagarto
  - build:torture
  - lagarto
  - torture

###################################
# setup tools

tools:build:
  tags: 
    - test
  stage: tools
  script:
    - mkdir -p piton/design/chip/tile/ariane
    - . piton/ariane_build_tools.sh
  artifacts:
    paths:
      - piton/design/chip/tile/ariane/tmp/
    expire_in: 1 hour

###################################
# try to build different configs with VCS

    #- ". /home/tools/riscv_vector_toolchain/set_env.sh"


build:msm-lagarto:
  tags: 
    - test
  stage: build:lagarto
  dependencies: 
    - tools:build
  script:
    - cd build
    - ../piton/tools/bin/sims -sys=manycore -x_tiles=1 -y_tiles=1 -msm_build -lagarto -config_rtl=BSC_RTL_SRAMS
    - "grep 'Errors: 0' sims.log"

build:msm-torture:
  tags: 
    - test
  stage: build:torture
  dependencies: 
    - tools:build
  script:
    - cd build
    - ../piton/tools/bin/sims -sys=manycore -x_tiles=1 -y_tiles=1 -msm_build -lagarto -config_rtl=BSC_RTL_SRAMS -config_rtl=OPENPITON_LAGARTO_COMMIT_LOG
    - "grep 'Errors: 0' sims.log"

##############################################################33333

test:rv64ui-v-add:
  stage: lagarto
  dependencies: 
    - build:msm-torture
  tags: 
    - test
  script:
    - cd build
    - ../piton/tools/bin/sims -sys=manycore -msm_run -x_tiles=1 -y_tiles=1 rv64ui-v-add.S -lagarto -precompiled -trap_offset=0x80000000 -rtl_timeout=1000000
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'Simulation -> PASS (HIT GOOD TRAP)' status.log"

test:rv64ui-v-add1:
  stage: lagarto
  dependencies: 
    - build:msm-torture
  tags: 
    - test
  script:
    - cd build
    - ../piton/tools/bin/sims -sys=manycore -msm_run -x_tiles=1 -y_tiles=1 rv64ui-v-add1.S -lagarto -precompiled -trap_offset=0x80000000 -rtl_timeout=1000000
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'Simulation -> PASS (HIT GOOD TRAP)' status.log"
