# Copyright 2018 ETH Zurich and University of Bologna.
# Copyright and related rights are licensed under the Solderpad Hardware
# License, Version 0.51 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
# or agreed to in writing, software, hardware and materials distributed under
# this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# Author: Michael Schaffner <schaffner@iis.ee.ethz.ch>, ETH Zurich
# Date: 26.11.2018
# Description: GitLab CI configuration script.

before_script:
  - . /eda/mentor/2020-21/scripts/QUESTA-CORE-PRIME_2020.4_RHELx86.sh
  - export QUESTA_HOME=/eda/mentor/2020-21/RHELx86/QUESTA-CORE-PRIME_2020.4
  # eda env mentor licence 
  - export MGLS_LICENSE_FILE=1717@epi03.bsc.es
  - export MGLS1_LICENSE_FILE=1717@epi01.bsc.es
  - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$MGLS_LICENSE_FILE:$MGLS1_LICENSE_FILE
  #- . ./piton/lagarto_setup.sh
  #- . ./piton/lagarto_build_tools.sh 

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - settings
  - build
  - regression1
  - regression2

build:lagarto:
  tags: 
    - settings
  stage: settings
  script:
  - . ./piton/lagarto_setup.sh
  - . ./piton/lagarto_build_tools.sh 

###################################
# Build                           #
###################################
 
build:lagarto:
  tags: 
    - test
  stage: build
  script:
    - cd build
    - sims -sys=manycore -x_tiles=1 -y_tiles=1 -msm_build -lagarto -config_rtl=BSC_RTL_SRAMS
    - "grep 'Errors: 0' sims.log"

build:lagarto-torture:
  tags: 
    - test
  stage: build
  script:
    - cd build
    - sims -sys=manycore -x_tiles=1 -y_tiles=1 -msm_build -lagarto -config_rtl=BSC_RTL_SRAMS -config_rtl=OPENPITON_LAGARTO_COMMIT_LOG
    - "grep 'Errors: 0' sims.log"

##############################################################
## Regression tests                                        ###
##############################################################
   
user_level_integer_physical:
  stage: regression1
  dependencies: 
    - build:lagarto-torture
  tags: 
    - test
  script:
    - cd build
    - sims -group=lagarto_tile1_asm_tests_p -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

user_level_integer_virtual:
  stage: regression2
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:
    - cd build
    - sims -group=lagarto_tile1_asm_tests_v -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

user_level_atomics_physical:
  stage: regression1
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:
    - cd build
    - sims -group=lagarto_tile1_amo_tests_p -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

user_level_atomics_virtual:
  stage: regression2
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:
    - cd build
    - sims -group=lagarto_tile1_amo_tests_v -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

user_level_mul_div_physical:
  stage: regression1
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:  
    - cd build
    - sims -group=lagarto_tile1_mul_div_tests_p -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

user_level_mul_div_virtual:
  stage: regression2
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:
    - cd build
    - sims -group=lagarto_tile1_mul_div_tests_v -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"
 
machine_levels:
  stage: regression2
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:  
    - cd build
    - sims -group=lagarto_tile1_machine_lvl_tests_p -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

supervisor_levels:
  stage: regression1
  dependencies:
    - build:lagarto-torture
  tags:
    - test
  script:
    - cd build
    - sims -group=lagarto_tile1_supervisor_lvl_tests_p -sim_type=msm
    - "cd 2*"
    - "regreport . -summary | tee regress.log"
    - "grep 'REGRESSION PASSED' regress.log"

